#+SETUPFILE: ~/.emacs.d/org-html-themes/setup/theme-readtheorg.setup
#+STARTUP: showall
#+Edited on <2018-10-09 ဂါ>



* Setup steps
1. Open Github account at https://github.com
2. Create Repo with calculater ruby 
3. Require Working Git Bash / Source tree
4. Require at least 1 code editor ( VS Code / Notepad ++ / Emacs / Vim / Sublime Text) 
5. Require  Ruby.
* Notes 
** Git by Phway Thant Chae
1. Project တည်ဆ​ောက်ထားခြင်း မရှိသ​ေးပါက  Github မှာ Project  ကိုအသစ်ဆ​ောက်ပါ။  မိမိစက်တွင် clone လုပ်ရန် "git clone URL"  ကို command တွင် ရိုက်ထည့်ပါ။  
2. Project တည်ဆ​ောက်ထားပြီးသားရှိပါက " git remote add origin URL "  command တွင် ရိုက်ထည့်ပါ။  ရှိပြီးသား project တွင် git ထည့်လိုပါက "git init" ပြုလုပ်ပါ။
3. Project အတွင်းရှိ ဖိုင်များ ၏ အခြေအနေကို သိလိုပါက "git status" ပြုလုပ်ပါ။
4. ပြောင်းလဲမှုပြုလုပ်ထားသောဖိုင်များကို  staging အဆင့်သို့ပေးပို့ရန် "git  add  <filename>" ပြုလုပ်ပါ။
5. Staging ပြုလုပ်ပြီးသောဖိုင်များကို commit လုပ်ရန် ' git commit -m "<commit message>"  '. 
6. Github သို့ပေးပို့ရန် " git push -u origin master " ပြုလုပ်ပါ။
7. Github မှ ဖိုင်များကို download ပြုလုပ်ရန် " git pull origin master" ပြုလုပ်ပါ။
8. မိမိပြုလုပ်ထားသော commit log များကို ကြည့်ရှုရန် " git log " ပြုလုပ်ပါ။
* Reading List and Notes for Internship program
** Ruby Reading List
1. [[https://launchschool.com/books/ruby/read/variables#gettingdatafromauser][Ruby Getting Data]]
2. [[https://www.tutorialspoint.com/ruby/ruby_loops.htm][Ruby Loops]]
3. [[http://ask.tiide.org/index.php?p=%2Fdiscussion%2Fcomment%2F72#Comment_72][Tiide.org training Videos]]
4. [[https://www.tutorialspoint.com/ruby/][Tutorial Point Ruby]]
** Git Reading List
1. [[http://try.github.io/][Try Github.io]]
2. [[http://marklodato.github.io/visual-git-guide/index-en.html][Visualization Git]]
3. [[https://www.syncfusion.com/ebooks/git][Git Succinctly]]
* Assignment 
** First Assignment (Git)
1. Create your own account in Github.
2. Create a repository called "Calculator" in Github. 
3. Git clone "Calculator" project in your local machine.
4. Create README.md in "Calculator project".  ( README.md should include brief introduction about the ruby calculator program )
5. Push ruby calculator program code and README.md to "Calculator" repo.
** Second Assignment (Calculator.rb) 
1. Calculator program မှာ ကိန်း ၂ ခုကို user ဆီက တောင်းပါမယ်။ ပြီးရင် အဲ့ကိန်း၂ခုရဲ့ ပေါင်းလဒ်၊ နုတ်လဒ်၊ မြေှာက်လဒ်၊ စားလဒ် နဲ့ အကြွင်း တို့ကို screen မှာပြပါ
2. အဲ့အဆင့်ပြီးရင် user ဆီက ကိန်း၂ခုကို ဘာလုပ်မှာလဲ ဆိုတာတောင်းပြီး တောင်းတဲ့ operation အတိုင်း ဆောင်ရွက်ပြီး result ကို ပြပါ။
3. အဲ့အဆင့်ပြီးရင် နောက် အဆင့်အနေနဲ့ user ကို ထပ်ပြီး operation (ပေါင်း၊ နုတ်၊ မြေှာက်၊ စား) လုပ်ချင်သေးလား။ မေးတာထည့်မယ်။ user က ထပ်လုပ်မယ် y ဆိုရင် ကိန်း၂ခုပြန်တောင်း။ operation (ပေါင်း၊ နုတ်၊ မြေှာက်၊ စား) ပြန်တောင်းပြီး အဖြေပြ။  ပြီးရင် ပေါင်း၊ နုတ်၊ မြေှာက်၊ စား လုပ်မှာလား ပြန်မေး၊ user က မလုပ်တော့ဘူး n ဆိုမှ program ပြီးမယ်။
4. user ရိုက်လိုက်တဲ့ operand 2 ခု၊ operator နဲ့ သူ့ result ကို File တစ်ခုမှာ save ရမှာပါ။ 
5. program 4 က user က ဘာ ရိုက်လိုက်တယ်. ဘာ result ထွက်လာတယ်. ဆိုတာကို file မှာ save လုပ်တာပါ
6. ဒါပြီးရင် ရေးခဲ့တဲ့ programs ၄ခုကို github မှာတင်ပေးပါ။
#+begin_danger
DeadLine - <2018-10-18 တေး>
#+end_danger

* FAQ
** Please tell me who you are ** error တက်ခဲ့လျှင်
- မိမိစက်ထဲရှိ git repositories တွင် username and email သတ်မှတ်ရန်
- "git config --global user.name "name" "
- "git config --global user.email "*****@gmail.com" "
** Project တည်ဆ​ောက်ထားခြင်း မရှိသ​ေးပါက  
- Github မှာ Project  ကိုအသစ်ဆ​ောက်ပါ။ 
- မိမိစက်တွင် clone လုပ်ရန် "git clone URL"  ကို command တွင် ရိုက်ထည့်ပါ။  
** Project တည်ဆ​ောက်ထားပြီးသားရှိပါက 
- " git remote add origin URL "  command တွင် ရိုက်ထည့်ပါ။  (or) ရှိပြီးသား project တွင် git ထည့်လိုပါက "git init" ပြုလုပ်ပါ။


